// web/src/Login.tsx
import { useState } from 'react';
import { api } from './api';
import type { User } from './types';

export function Login({ onLogin }: { onLogin: (u: User, token: string) => void }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [err, setErr] = useState('');

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const r = await api.login(username, password);
      onLogin(r.user, r.token);
    } catch (e: any) {
      setErr(e.message);
    }
  };

  return (
    <div className="flex h-full items-center justify-center bg-slate-900 text-slate-100">
      <form onSubmit={submit} className="w-80 rounded-xl bg-slate-800 p-6 shadow-xl">
        <h1 className="mb-4 text-xl">足浴经营系统 · 登录</h1>
        <input className="mb-3 w-full rounded bg-slate-700 px-3 py-2 outline-none" placeholder="账号" value={username} onChange={e => setUsername(e.target.value)} />
        <input className="mb-3 w-full rounded bg-slate-700 px-3 py-2 outline-none" type="password" placeholder="密码" value={password} onChange={e => setPassword(e.target.value)} />
        {err && <div className="mb-3 text-sm text-red-400">{err}</div>}
        <button className="w-full rounded bg-cyan-500 py-2 font-medium">登录</button>
      </form>
    </div>
  );
}

// web/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { api } from '../api';
import type { User } from '../types';

const emit = defineEmits<{ (e: 'login', u: User, t: string): void }>();
const username = ref('');
const password = ref('');
const err = ref('');

const submit = async () => {
  try {
    const r = await api.login(username.value, password.value);
    emit('login', r.user, r.token);
  } catch (e: any) {
    err.value = e.message;
  }
};
</script>

<template>
  <div class="flex h-full items-center justify-center bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900">
    <form @submit.prevent="submit" class="w-96 rounded-2xl border border-cyan-500/20 bg-slate-800/70 p-8 shadow-2xl backdrop-blur">
      <div class="mb-6 text-center">
        <div class="text-4xl">🦶</div>
        <h1 class="mt-2 text-xl font-semibold text-slate-100">足浴经营系统</h1>
        <p class="text-sm text-slate-400">多部门智能经营平台</p>
      </div>
      <input v-model="username" class="mb-3 w-full rounded-lg bg-slate-700/60 px-4 py-3 text-slate-100 outline-none focus:ring-2 focus:ring-cyan-500" placeholder="账号" />
      <input v-model="password" type="password" class="mb-3 w-full rounded-lg bg-slate-700/60 px-4 py-3 text-slate-100 outline-none focus:ring-2 focus:ring-cyan-500" placeholder="密码" />
      <div v-if="err" class="mb-3 text-sm text-red-400">{{ err }}</div>
      <button class="w-full rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 py-3 font-medium text-white shadow-lg transition hover:from-cyan-400 hover:to-blue-400">登录</button>
      <p class="mt-4 text-center text-xs text-slate-500">默认账号 boss/boss123 · mgr/mgr123</p>
    </form>
  </div>
</template>
