// web/src/ShopList.tsx
import { useEffect, useState } from 'react';
import { api } from './api';
import type { Shop, User } from './types';

export function ShopList({
  user, period, onPeriod, onPick, onDashboard, onLogout,
}: {
  user: User | null;
  period: string;
  onPeriod: (p: string) => void;
  onPick: (s: Shop) => void;
  onDashboard: () => void;
  onLogout: () => void;
}) {
  const [shops, setShops] = useState<Shop[]>([]);
  const [err, setErr] = useState('');

  useEffect(() => {
    api.shops().then(setShops).catch(e => setErr(e.message));
  }, []);

  return (
    <div className="h-full bg-slate-900 text-slate-100">
      <header className="flex items-center justify-between border-b border-slate-700 p-4">
        <h1 className="text-lg">店铺列表</h1>
        <div className="flex items-center gap-3 text-sm">
          <button onClick={onDashboard} className="rounded bg-cyan-500 px-3 py-1 text-slate-900">📊 数据大屏</button>
          <input type="month" value={period} onChange={e => onPeriod(e.target.value)} className="rounded bg-slate-800 px-2 py-1" />
          <span>{user?.name}</span>
          <button onClick={onLogout} className="text-cyan-400">退出</button>
        </div>
      </header>
      <main className="grid grid-cols-2 gap-4 p-6 md:grid-cols-3">
        {err && <div className="text-red-400">{err}</div>}
        {shops.map(s => (
          <button key={s.id} onClick={() => onPick(s)} className="rounded-xl bg-slate-800 p-6 text-left hover:ring-2 hover:ring-cyan-500">
            <div className="text-base font-medium">{s.name}</div>
            <div className="text-xs text-slate-400">{s.business_name}</div>
          </button>
        ))}
      </main>
    </div>
  );
}

// web/src/views/ShopList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { api } from '../api';
import type { Shop, User } from '../types';

defineProps<{ user: User | null; period: string }>();
const emit = defineEmits<{
  (e: 'update:period', p: string): void;
  (e: 'pick', s: Shop): void;
  (e: 'dashboard'): void;
  (e: 'logout'): void;
}>();

const shops = ref<Shop[]>([]);
const err = ref('');
onMounted(() => { api.shops().then(r => shops.value = r).catch(e => err.value = e.message); });
</script>

<template>
  <div class="h-full bg-gradient-to-b from-slate-900 to-slate-950 text-slate-100">
    <header class="flex items-center justify-between border-b border-slate-700/50 p-5">
      <div>
        <h1 class="text-xl font-semibold">店铺列表</h1>
        <p class="text-sm text-slate-400">选择门店进入当月工作簿</p>
      </div>
      <div class="flex items-center gap-3 text-sm">
        <button @click="emit('dashboard')" class="rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 px-4 py-2 font-medium text-white shadow transition hover:from-cyan-400 hover:to-blue-400">📊 数据大屏</button>
        <input type="month" :value="period" @change="emit('update:period', ($event.target as HTMLInputElement).value)" class="rounded-lg bg-slate-800 px-3 py-2" />
        <span class="text-slate-300">{{ user?.name }}</span>
        <button @click="emit('logout')" class="text-cyan-400 hover:text-cyan-300">退出</button>
      </div>
    </header>
    <main class="grid grid-cols-1 gap-5 p-6 md:grid-cols-2 lg:grid-cols-3">
      <div v-if="err" class="text-red-400">{{ err }}</div>
      <button v-for="s in shops" :key="s.id" @click="emit('pick', s)" class="group rounded-2xl border border-slate-700/50 bg-slate-800/50 p-6 text-left transition hover:-translate-y-1 hover:border-cyan-500/50 hover:shadow-xl hover:shadow-cyan-500/10">
        <div class="flex items-center justify-between">
          <div class="text-lg font-medium">{{ s.name }}</div>
          <div class="text-slate-500 transition group-hover:text-cyan-400">→</div>
        </div>
        <div class="mt-1 text-xs text-slate-400">{{ s.business_name }}</div>
      </button>
    </main>
  </div>
</template>
